services:
  json-server:
    build:
      context: ./json-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./json-server/db.json:/data/db.json
    command: "json-server /data/db.json --port 3000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 10s
      timeout: 1m
      retries: 5
      start_period: 15s